title: "New School Revolution"
description: "There Are No Pointy-Eared Elves Here."
author: yochaigal
email: yochaigal@gmail.com
baseurl: ""
url:
title_description: "There Are No Pointy-Eared Elves Here."
title_image: "/img/layard_dragon.png"
google_analytics:
disqus_account: https-newschoolrevolution-com
github_repository: https://github.com/yochaigal/newschoolrevolution/tree/gh-pages
addthis_id:
post_limit: 10

twitter_username: yochaigal1
github_username: yochaigal
reddit_username: yochaigal

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title
exclude: [vendor]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
