# Site settings
title: "New School Revolution"
description: "A blog about dragons. Or something."
author: yochaigal
email: yochaigal@gmail.com
baseurl: ""
url: https://newschoolrevolution.com
title_description: "A blog about dragons. Or something."
title_image: "/img/layard_dragon.png"
google_analytics:
disqus_account: yochaigal
github_repository: https://github.com/yochaigal/newschoolrevolution/tree/gh-pages
addthis_id:
post_limit: 10

# Social usernames/URLs
twitter_username: yochaigal1
github_username: yochaigal
reddit_username: yochaigal

# Footer
#footer_left: "Theme created by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
