title: "New School Revolution"
description: "There Are No Pointy-Eared Elves Here."
title_description: "There Are No Pointy-Eared Elves Here."
title_image: "/img/positronic_nsr.png"
author: yochaigal
name: Yochai Gal
email: yochaigal@gmail.com
picture: "/img/positronic_nsr.png"
url: https://newschoolrevolution.com
baseurl: ''
rss: http://newschoolrevolution.com/feed.xml
disqus_account: https-newschoolrevolution-com
github_repository: https://github.com/yochaigal/newschoolrevolution/tree/gh-pages
logo: "/img/positronic_nsr.png"
google_analytics:
addthis_id:
post_limit: 10
twitter_username: yochaigal1
github_username: yochaigal
reddit_username: yochaigal
mastodon_username: yochaigal

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

author:
  name: Yochai Gal
  email: yochaigal@gmail.com
permalink: /:year/:month/:day/:title
exclude: [vendor]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
