theme: jekyll-theme-dinky
title: new school revolution
github: is_project_page: false
email: yochaigal@gmail.com
shorttitle: New School revolution
baseurl: "/posts"
url: "https://newschoolrevolution.com"
github username: yochaigal
