title: New School Revolution
description: NSR RPGs, Yo!
author: yochaigal
email: yochaigal@gmail.com
shorttitle: NSR
baseurl: "/posts"
url: "https://newschoolrevolution.com"
github_username:  exposit
show_downloads: false
theme: jekyll-theme-midnight
plugins: [jekyll-paginate]
permalink: /:year/:month/:day/:title/
